import React, { useState } from 'react';
import { Users, Shield, Sparkles, BookOpen, Compass, Dice5, ArrowRight, Dices, Shuffle, Wand2, Bot, UserCheck, AlertCircle, Camera } from 'lucide-react';
import { Character, CharacterClass, Race } from '../types';
import {
  SETTING_PRESETS,
  SCENARIO_HOOKS,
  createDefaultCharacter,
  rollDndStats,
  generateRandomName,
  generateFantasyBackstory,
  randomizeCharacter,
  getStatModifier,
  formatModifier,
  ALL_CLASSES,
  ALL_RACES,
} from '../data/presets';
import { soundManager } from '../utils/audio';
import { PortraitEditorModal } from './PortraitEditorModal';
import { getAutoGeneratedPortrait } from '../utils/portrait';

interface PlayerSetupProps {
  onStartCampaign: (
    playerCount: 1 | 2 | 3 | 4,
    party: Character[],
    settingName: string,
    scenarioHook: string,
    wikiTopics: string[],
    customNotes: string
  ) => void;
  isLoading: boolean;
  error: string | null;
}

export const PlayerSetup: React.FC<PlayerSetupProps> = ({
  onStartCampaign,
  isLoading,
  error,
}) => {
  const [playerCount, setPlayerCount] = useState<1 | 2 | 3 | 4>(2);
  const [party, setParty] = useState<Character[]>(() => {
    const c1 = createDefaultCharacter('p1', 1, 'Fighter', 'Human');
    const c2 = createDefaultCharacter('p2', 2, 'Wizard', 'Elf', false, [c1.name], [c1.backstory]);
    return [c1, c2];
  });

  // Validation Error for Hero Gender
  const [genderError, setGenderError] = useState<string | null>(null);

  // Require user to select a world setting (starts empty)
  const [selectedSettingId, setSelectedSettingId] = useState<string>('');
  const [customSetting, setCustomSetting] = useState<string>('');
  const [selectedHook, setSelectedHook] = useState<string>('');
  const [customHook, setCustomHook] = useState<string>('');
  const [selectedWikiTopics, setSelectedWikiTopics] = useState<string[]>([]);
  const [customNotes, setCustomNotes] = useState<string>('');
  const [activeTab, setActiveTab] = useState<'party' | 'world'>('party');
  const [editingPortraitIndex, setEditingPortraitIndex] = useState<number | null>(null);

  const validateGenderSelection = (): boolean => {
    const unselected = party.some((c) => !c.gender);
    if (unselected) {
      soundManager.playDiceRoll();
      setGenderError('gender selection required.');
      setActiveTab('party');
      return false;
    }
    setGenderError(null);
    return true;
  };

  // Random Scenario Selector
  const handleSelectRandomScenario = () => {
    soundManager.playDiceRoll();
    const randomPreset = SETTING_PRESETS[Math.floor(Math.random() * SETTING_PRESETS.length)];
    setSelectedSettingId(randomPreset.id);
    setSelectedWikiTopics(randomPreset.wikiTopics);

    const randomHook = SCENARIO_HOOKS[Math.floor(Math.random() * SCENARIO_HOOKS.length)];
    setSelectedHook(randomHook);
  };

  // Solo Player + AI Party Quick Preset (1 Human + 3 AI Companions)
  const handleSetSoloAiParty = () => {
    soundManager.playPageTurn();
    setPlayerCount(4);
    const c1 = createDefaultCharacter('p1', 1, 'Fighter', 'Human', false);
    const c2 = createDefaultCharacter('p2', 2, 'Wizard', 'Elf', true, [c1.name], [c1.backstory]);
    const c3 = createDefaultCharacter('p3', 3, 'Cleric', 'Dwarf', true, [c1.name, c2.name], [c1.backstory, c2.backstory]);
    const c4 = createDefaultCharacter('p4', 4, 'Rogue', 'Tiefling', true, [c1.name, c2.name, c3.name], [c1.backstory, c2.backstory, c3.backstory]);
    setParty([c1, c2, c3, c4]);
  };

  // All Human Party Quick Preset
  const handleSetAllHumanParty = () => {
    soundManager.playPageTurn();
    setParty((prev) => prev.map((char) => ({ ...char, isAiControlled: false })));
  };

  // Handle changing player count (1, 2, 3, or 4)
  const handlePlayerCountChange = (count: 1 | 2 | 3 | 4) => {
    soundManager.playPageTurn();
    setPlayerCount(count);
    const newParty: Character[] = [];
    const classDefaults: CharacterClass[] = ['Fighter', 'Wizard', 'Rogue', 'Cleric'];
    const raceDefaults: Race[] = ['Human', 'Elf', 'Dwarf', 'Tiefling'];

    for (let i = 1; i <= count; i++) {
      if (party[i - 1]) {
        newParty.push({ ...party[i - 1], playerName: `Player ${i}` });
      } else {
        const existingNames = newParty.map((c) => c.name);
        const existingBackstories = newParty.map((c) => c.backstory);
        newParty.push(
          createDefaultCharacter(
            `p${i}`,
            i,
            classDefaults[i - 1],
            raceDefaults[i - 1],
            false,
            existingNames,
            existingBackstories
          )
        );
      }
    }
    setParty(newParty);
  };

  // Randomize ALL party members (guaranteeing unique names & backstories)
  const handleRandomizeAllParty = () => {
    soundManager.playDiceRoll();
    setParty((prev) => {
      const newParty: Character[] = [];
      prev.forEach((char, idx) => {
        const existingNames = newParty.map((c) => c.name);
        const existingBackstories = newParty.map((c) => c.backstory);
        newParty.push(randomizeCharacter(char, idx + 1, existingNames, existingBackstories));
      });
      return newParty;
    });
  };

  // Randomize a single character entirely
  const handleRandomizeSingleCharacter = (index: number) => {
    soundManager.playDiceRoll();
    setParty((prev) => {
      const next = [...prev];
      const otherNames = next.filter((_, idx) => idx !== index).map((c) => c.name);
      const otherBackstories = next.filter((_, idx) => idx !== index).map((c) => c.backstory);
      next[index] = randomizeCharacter(next[index], index + 1, otherNames, otherBackstories);
      return next;
    });
  };

  // Randomize only Name (and regenerate backstory to keep name in sync and unique)
  const handleRandomizeName = (index: number) => {
    soundManager.playDiceRoll();
    setParty((prev) => {
      const next = [...prev];
      const char = next[index];
      const otherNames = next.filter((_, idx) => idx !== index).map((c) => c.name);
      const otherBackstories = next.filter((_, idx) => idx !== index).map((c) => c.backstory);
      const newName = generateRandomName(char.characterClass, char.race, otherNames);
      const newBackstory = generateFantasyBackstory(newName, char.race, char.characterClass, otherBackstories, char.gender);
      next[index] = { ...char, name: newName, backstory: newBackstory };
      return next;
    });
  };

  // Randomize only Stats using standard 4d6 Drop Lowest
  const handleRandomizeStats = (index: number) => {
    soundManager.playDiceRoll();
    setParty((prev) => {
      const next = [...prev];
      const char = next[index];
      const newStats = rollDndStats();
      next[index] = { ...char, stats: newStats };
      return next;
    });
  };

  // Randomize Backstory (generated 3-5 high-quality sentences, strictly unique)
  const handleRandomizeBackstory = (index: number) => {
    soundManager.playDiceRoll();
    setParty((prev) => {
      const next = [...prev];
      const char = next[index];
      const otherBackstories = next.filter((_, idx) => idx !== index).map((c) => c.backstory);
      const newBackstory = generateFantasyBackstory(char.name, char.race, char.characterClass, otherBackstories, char.gender);
      next[index] = { ...char, backstory: newBackstory };
      return next;
    });
  };

  // Update a specific character in the party
  const handleUpdateCharacter = (index: number, updates: Partial<Character>) => {
    soundManager.playPageTurn();
    setParty((prev) => {
      const next = [...prev];
      const current = next[index];

      const newGender = updates.gender !== undefined ? updates.gender : current.gender;
      let updatedChar = { ...current, ...updates, gender: newGender };

      // Re-initialize character stats/HP/AC if class or race changes
      if (updates.characterClass || updates.race) {
        const otherNames = next.filter((_, idx) => idx !== index).map((c) => c.name);
        const otherBackstories = next.filter((_, idx) => idx !== index).map((c) => c.backstory);
        const fresh = createDefaultCharacter(
          current.id,
          index + 1,
          updates.characterClass || current.characterClass,
          updates.race || current.race,
          current.isAiControlled,
          otherNames,
          otherBackstories,
          newGender
        );
        updatedChar = {
          ...fresh,
          gender: newGender,
          name: updates.name !== undefined ? updates.name : fresh.name,
          playerName: current.playerName,
          backstory: updates.backstory || fresh.backstory,
          isAiControlled: updates.isAiControlled !== undefined ? updates.isAiControlled : current.isAiControlled,
        };
      }

      next[index] = updatedChar;

      // Clear error if all party members now have a gender chosen
      if (next.every((c) => !!c.gender)) {
        setGenderError(null);
      }

      return next;
    });
  };

  // Handle setting preset change
  const handleSettingPresetChange = (presetId: string) => {
    soundManager.playPageTurn();
    setSelectedSettingId(presetId);
    const preset = SETTING_PRESETS.find((s) => s.id === presetId);
    if (preset) {
      setSelectedHook(preset.defaultHook);
      setSelectedWikiTopics(preset.wikiTopics);
      soundManager.updateContext(preset.name, preset.tagline, false);
    }
  };

  const currentPreset = SETTING_PRESETS.find((s) => s.id === selectedSettingId);
  const effectiveSetting = selectedSettingId === 'custom' ? customSetting || 'Custom Mythic Realm' : currentPreset?.name || 'Mythic Realm';
  const effectiveHook = selectedHook === 'custom' ? customHook || 'An unexplained discovery' : selectedHook;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateGenderSelection()) return;
    if (!selectedSettingId) return;
    soundManager.playSuccess();
    onStartCampaign(
      playerCount,
      party,
      effectiveSetting,
      effectiveHook,
      selectedWikiTopics,
      customNotes
    );
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 text-stone-100">
      {/* Welcome Banner */}
      <div className="bg-gradient-to-r from-amber-950/80 via-stone-900 to-amber-950/80 border border-amber-800/50 rounded-2xl p-6 mb-8 shadow-2xl relative overflow-hidden">
        <div className="absolute -right-10 -bottom-10 opacity-10 pointer-events-none">
          <Sparkles className="w-64 h-64 text-amber-400" />
        </div>

        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-xl bg-amber-600/20 border border-amber-500/40 flex items-center justify-center shrink-0 text-amber-300">
            <Compass className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <h2 className="text-2xl font-serif font-bold text-amber-100 mb-2">
              Charlie's Custom Adventures
            </h2>
            <p className="text-stone-300 text-sm leading-relaxed">
              Generate a unique branching adventure for one to four players. Start here to have some fun.
            </p>
          </div>
        </div>
      </div>

      {error && (
        <div className="mb-6 p-4 rounded-xl bg-red-950/80 border border-red-800 text-red-200 text-sm flex items-center justify-between">
          <span>⚠️ {error}</span>
        </div>
      )}

      {genderError && (
        <div className="mb-6 p-4 rounded-xl bg-red-950/90 border border-red-700 text-red-200 text-sm font-medium flex items-center justify-between shadow-lg animate-bounce">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-red-400 shrink-0" />
            <span className="font-bold">{genderError}</span>
          </div>
          <button
            type="button"
            onClick={() => setGenderError(null)}
            className="text-xs text-red-300 hover:text-white underline cursor-pointer"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* Main Form */}
      <form onSubmit={handleSubmit} className="space-y-8">
        {/* Step 1: Player Count & Navigation Tabs */}
        <div className="bg-stone-900 border border-stone-800 rounded-2xl p-6 shadow-xl">
          <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 mb-6">
            <div>
              <h3 className="text-lg font-serif font-bold text-amber-100 flex items-center gap-2">
                <Users className="w-5 h-5 text-amber-400" />
                Select Party Size
              </h3>
              <p className="text-xs text-stone-400">
                Play solo with 1 adventurer, or co-op with 2, 3, or 4 players taking turns.
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3 w-full lg:w-auto justify-between lg:justify-end">
              {/* Player Count Selector */}
              <div className="flex items-center gap-1.5 bg-stone-950 p-1.5 rounded-xl border border-stone-800">
                {([1, 2, 3, 4] as const).map((num) => (
                  <button
                    key={num}
                    type="button"
                    onClick={() => handlePlayerCountChange(num)}
                    className={`px-3 sm:px-4 py-2 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                      playerCount === num
                        ? 'bg-amber-600 text-stone-950 shadow-md scale-105'
                        : 'text-stone-400 hover:text-stone-200 hover:bg-stone-800'
                    }`}
                  >
                    {num === 1 ? '1 Player' : `${num} Players`}
                  </button>
                ))}
              </div>

              {/* Randomize All Button */}
              <button
                type="button"
                onClick={handleRandomizeAllParty}
                className="px-4 py-2 rounded-xl bg-amber-950 hover:bg-amber-900 border border-amber-600/70 text-amber-200 text-xs font-serif font-bold transition-all flex items-center gap-2 cursor-pointer shadow-md hover:scale-105 shrink-0"
                title="Randomize race, class, stats (4d6 drop lowest), name, and backstory for all players"
              >
                <Shuffle className="w-4 h-4 text-amber-400" />
                <span>Randomize All Players</span>
              </button>
            </div>
          </div>

          {/* Navigation Tabs (Party vs World Setting) */}
          <div className="flex flex-wrap border-b border-stone-800 gap-4 sm:gap-6">
            <button
              type="button"
              onClick={() => setActiveTab('party')}
              className={`pb-3 text-sm font-semibold flex items-center gap-2 border-b-2 transition-colors cursor-pointer ${
                activeTab === 'party'
                  ? 'border-amber-500 text-amber-200'
                  : 'border-transparent text-stone-400 hover:text-stone-200'
              }`}
            >
              <Shield className="w-4 h-4 text-amber-400" />
              1. Character Creation ({party.length})
            </button>
            <button
              type="button"
              onClick={() => {
                if (validateGenderSelection()) {
                  setActiveTab('world');
                }
              }}
              className={`pb-3 text-sm font-semibold flex items-center gap-2 border-b-2 transition-colors cursor-pointer ${
                activeTab === 'world'
                  ? 'border-amber-500 text-amber-200'
                  : !selectedSettingId
                  ? 'border-amber-500/80 text-amber-300 animate-pulse'
                  : 'border-transparent text-stone-400 hover:text-stone-200'
              }`}
            >
              <BookOpen className="w-4 h-4 text-amber-400" />
              2. Campaign Setting & Atmosphere
              {!selectedSettingId && (
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-amber-500 text-stone-950 font-bold uppercase tracking-wider">
                  Select
                </span>
              )}
            </button>
          </div>
        </div>

        {/* TAB 1: PARTY CREATION */}
        {activeTab === 'party' && (
          <div className="space-y-6">
            {/* Quick Mode Preset Banner */}
            <div className="bg-stone-900 border border-amber-900/40 rounded-xl p-4 flex flex-col sm:flex-row items-center justify-between gap-3 shadow-md">
              <div className="flex items-center gap-2">
                <Bot className="w-5 h-5 text-amber-400 shrink-0" />
                <p className="text-xs text-stone-300">
                  <strong>Playing Solo?</strong> You can play alone while having automated AI companions in your party to handle combat and assist on quests!
                </p>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <button
                  type="button"
                  onClick={handleSetSoloAiParty}
                  className="px-3 py-1.5 rounded-lg bg-stone-950 hover:bg-amber-950 border border-stone-800 hover:border-amber-600/80 text-stone-300 hover:text-amber-200 text-xs font-medium transition-all flex items-center gap-1.5 cursor-pointer shadow-sm"
                  title="Sets a 4-hero party with Player 1 as You, and Players 2-4 as AI Companions"
                >
                  <Bot className="w-3.5 h-3.5 text-amber-400" />
                  <span>1 Human + 3 AI Companions</span>
                </button>
                <button
                  type="button"
                  onClick={handleSetAllHumanParty}
                  className="px-3 py-1.5 rounded-lg bg-stone-950 hover:bg-stone-800 border border-stone-800 text-stone-300 text-xs font-medium transition-all flex items-center gap-1.5 cursor-pointer"
                  title="Sets all party members to be controlled by human players"
                >
                  <UserCheck className="w-3.5 h-3.5 text-stone-400" />
                  <span>All Human Players</span>
                </button>
              </div>
            </div>

            <div className={`grid gap-6 ${
              playerCount === 1 ? 'grid-cols-1 max-w-xl mx-auto' :
              playerCount === 2 ? 'grid-cols-1 md:grid-cols-2' :
              playerCount === 3 ? 'grid-cols-1 md:grid-cols-3' :
              'grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-4'
            }`}>
              {party.map((char, index) => (
                <div
                  key={char.id}
                  className={`bg-stone-900 border rounded-2xl p-5 shadow-lg flex flex-col justify-between hover:border-amber-600/50 transition-all relative group ${
                    char.isAiControlled ? 'border-amber-700/60' : 'border-stone-800'
                  }`}
                >
                  <div>
                    <div className="flex items-center justify-between mb-3 border-b border-stone-800 pb-3">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-bold text-amber-400 uppercase tracking-wider bg-amber-950/60 px-2.5 py-1 rounded-md border border-amber-800/40">
                          Player {index + 1}
                        </span>
                        <span className="text-xl">{char.avatar}</span>
                      </div>

                      {/* Quick Full Character Randomizer */}
                      <button
                        type="button"
                        onClick={() => handleRandomizeSingleCharacter(index)}
                        className="px-2.5 py-1 rounded-lg bg-stone-950 hover:bg-amber-950 border border-stone-800 hover:border-amber-600 text-stone-300 hover:text-amber-200 text-[11px] font-medium transition-all flex items-center gap-1 cursor-pointer"
                        title="Randomize this hero's entire build"
                      >
                        <Shuffle className="w-3 h-3 text-amber-400" />
                        <span>Randomize</span>
                      </button>
                    </div>

                    {/* Profile Picture Section */}
                    <div className="mb-4 bg-stone-950 p-2.5 rounded-xl border border-stone-800/80 flex items-center justify-between">
                      <div className="flex items-center gap-2.5">
                        <div className="relative group shrink-0">
                          <img
                            src={char.portraitUrl || getAutoGeneratedPortrait(char.race, char.characterClass, char.name, char.gender)}
                            alt={char.name}
                            referrerPolicy="no-referrer"
                            className="w-12 h-12 rounded-xl object-cover border border-amber-500/70 shadow bg-stone-900"
                          />
                          <button
                            type="button"
                            onClick={() => setEditingPortraitIndex(index)}
                            className="absolute -bottom-1 -right-1 p-1 bg-amber-500 hover:bg-amber-400 text-stone-950 rounded-full shadow cursor-pointer transition-transform hover:scale-110"
                            title="Edit Character Profile Picture"
                          >
                            <Camera className="w-3 h-3" />
                          </button>
                        </div>
                        <div>
                          <span className="block text-xs font-bold text-stone-200">
                            Profile Picture
                          </span>
                          <span className="block text-[10px] text-stone-400 leading-tight">
                            Auto-generated
                          </span>
                        </div>
                      </div>

                      <button
                        type="button"
                        onClick={() => setEditingPortraitIndex(index)}
                        className="px-2.5 py-1 rounded-lg bg-stone-900 hover:bg-amber-950 border border-stone-700 hover:border-amber-600/80 text-amber-300 text-[11px] font-bold transition-all flex items-center gap-1 cursor-pointer"
                      >
                        <Camera className="w-3 h-3 text-amber-400" />
                        <span>Edit</span>
                      </button>
                    </div>

                    {/* AI Control Toggle Switch */}
                    <div className="mb-4 bg-stone-950/90 p-2.5 rounded-xl border border-stone-800/80 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        {char.isAiControlled ? (
                          <Bot className="w-4 h-4 text-amber-400 animate-pulse" />
                        ) : (
                          <UserCheck className="w-4 h-4 text-emerald-400" />
                        )}
                        <div>
                          <span className="block text-xs font-bold text-stone-200">
                            {char.isAiControlled ? 'AI Companion' : 'Human Player'}
                          </span>
                          <span className="block text-[10px] text-stone-400">
                            {char.isAiControlled ? 'AI manages combat turns' : 'Controlled by player'}
                          </span>
                        </div>
                      </div>
                      <label className="relative inline-flex items-center cursor-pointer">
                        <input
                          type="checkbox"
                          checked={!!char.isAiControlled}
                          onChange={(e) => handleUpdateCharacter(index, { isAiControlled: e.target.checked })}
                          className="sr-only peer"
                        />
                        <div className="w-8 h-4.5 bg-stone-800 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-stone-300 after:border-stone-300 after:border after:rounded-full after:h-3.5 after:w-3.5 after:transition-all peer-checked:bg-amber-600"></div>
                      </label>
                    </div>

                  {/* Character Name & Randomize Name Button */}
                  <div className="mb-4">
                    <div className="flex items-center justify-between mb-1">
                      <label className="block text-xs font-medium text-stone-300">
                        Hero Name
                      </label>
                      <button
                        type="button"
                        onClick={() => handleRandomizeName(index)}
                        className="text-[10px] text-amber-400 hover:text-amber-200 flex items-center gap-1 cursor-pointer transition-colors"
                        title="Generate a random fantasy name for this race & class"
                      >
                        <Wand2 className="w-3 h-3" />
                        <span>Random Name</span>
                      </button>
                    </div>
                    <input
                      type="text"
                      value={char.name}
                      onChange={(e) => handleUpdateCharacter(index, { name: e.target.value })}
                      className="w-full bg-stone-950 border border-stone-800 rounded-lg px-3 py-2 text-sm text-stone-100 focus:outline-none focus:border-amber-500"
                      placeholder="e.g. Eldrin, Valerius"
                      required
                    />
                  </div>

                  {/* Gender Selection */}
                  <div className="mb-4">
                    <div className="flex items-center justify-between mb-1.5">
                      <label className="block text-xs font-medium text-stone-300">
                        Hero Gender
                      </label>
                      {char.gender && (
                        <span className="text-[10px] text-amber-400 font-mono font-bold bg-amber-950/80 px-2 py-0.5 rounded border border-amber-800/50">
                          {char.gender === 'Male'
                            ? 'he/him'
                            : char.gender === 'Female'
                            ? 'she/her'
                            : 'they/them'}
                        </span>
                      )}
                    </div>
                    <div
                      className={`grid grid-cols-3 gap-1.5 p-1 bg-stone-950 border rounded-xl transition-all ${
                        !char.gender && genderError
                          ? 'border-red-500 ring-2 ring-red-500/50 shadow-red-900/30'
                          : 'border-stone-800'
                      }`}
                    >
                      {(['Male', 'Female', "I'd rather not say"] as const).map((g) => {
                        const isSelected = char.gender === g;
                        return (
                          <button
                            key={g}
                            type="button"
                            onClick={() => {
                              const otherBackstories = party
                                .filter((_, idx) => idx !== index)
                                .map((c) => c.backstory);
                              const updatedBackstory = generateFantasyBackstory(
                                char.name,
                                char.race,
                                char.characterClass,
                                otherBackstories,
                                g
                              );
                              handleUpdateCharacter(index, {
                                gender: g,
                                backstory: updatedBackstory,
                              });
                            }}
                            className={`py-1.5 px-1 rounded-lg text-[11px] font-medium transition-all cursor-pointer text-center ${
                              isSelected
                                ? 'bg-amber-600 text-stone-950 font-bold shadow-md scale-[1.02]'
                                : 'text-stone-400 hover:text-stone-200 hover:bg-stone-800/80'
                            }`}
                          >
                            {g === "I'd rather not say" ? "I'd rather not say" : g}
                          </button>
                        );
                      })}
                    </div>
                  </div>

                  {/* Class & Race */}
                  <div className="grid grid-cols-2 gap-3 mb-4">
                    <div>
                      <label className="block text-xs font-medium text-stone-400 mb-1">
                        D&D 5E Class
                      </label>
                      <select
                        value={char.characterClass}
                        onChange={(e) =>
                          handleUpdateCharacter(index, {
                            characterClass: e.target.value as CharacterClass,
                          })
                        }
                        className="w-full bg-stone-950 border border-stone-800 rounded-lg px-2.5 py-2 text-xs text-stone-100 focus:outline-none focus:border-amber-500"
                      >
                        {ALL_CLASSES.map((cls) => (
                          <option key={cls} value={cls}>
                            {cls}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div>
                      <label className="block text-xs font-medium text-stone-400 mb-1">
                        Race / Ancestry
                      </label>
                      <select
                        value={char.race}
                        onChange={(e) =>
                          handleUpdateCharacter(index, {
                            race: e.target.value as Race,
                          })
                        }
                        className="w-full bg-stone-950 border border-stone-800 rounded-lg px-2.5 py-2 text-xs text-stone-100 focus:outline-none focus:border-amber-500"
                      >
                        {ALL_RACES.map((rc) => (
                          <option key={rc} value={rc}>
                            {rc}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>

                  {/* Character Stats & 4d6 Roll Button */}
                  <div className="bg-stone-950 rounded-xl p-3 border border-stone-800 mb-4">
                    <div className="text-[10px] text-stone-400 uppercase tracking-wider mb-2 font-bold flex items-center justify-between">
                      <span className="flex items-center gap-1">
                        <span>D&D 5E Stats</span>
                        <span className="text-[9px] text-stone-500 font-normal lowercase">(4d6 drop lowest)</span>
                      </span>
                      <button
                        type="button"
                        onClick={() => handleRandomizeStats(index)}
                        className="text-amber-400 hover:text-amber-200 text-[10px] font-bold flex items-center gap-1 transition-colors cursor-pointer"
                        title="Roll stats using standard 4d6 drop lowest rule"
                      >
                        <Dices className="w-3.5 h-3.5" />
                        <span>Roll 4d6</span>
                      </button>
                    </div>
                    <div className="grid grid-cols-6 gap-1 text-center text-xs">
                      {([
                        { key: 'str', label: 'STR', val: char.stats.str },
                        { key: 'dex', label: 'DEX', val: char.stats.dex },
                        { key: 'con', label: 'CON', val: char.stats.con },
                        { key: 'int', label: 'INT', val: char.stats.int },
                        { key: 'wis', label: 'WIS', val: char.stats.wis },
                        { key: 'cha', label: 'CHA', val: char.stats.cha },
                      ] as const).map((st) => {
                        const mod = getStatModifier(st.val);
                        return (
                          <div key={st.key} className="bg-stone-900 p-1 rounded border border-stone-800/80">
                            <div className="text-[9px] text-stone-400">{st.label}</div>
                            <div className="font-bold text-amber-200 text-xs">{st.val}</div>
                            <div className="text-[9px] text-stone-500 font-mono">{formatModifier(mod)}</div>
                          </div>
                        );
                      })}
                    </div>
                    <div className="mt-2 pt-2 border-t border-stone-900 flex justify-between text-[11px] text-amber-300 font-mono">
                      <span>Hit Points: <strong>{char.hp}</strong></span>
                      <span>Armor Class: <strong>{char.ac}</strong></span>
                    </div>
                  </div>

                  {/* Backstory & Backstory Randomizer */}
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="block text-xs font-medium text-stone-300">
                        Backstory & Motivation
                      </label>
                      <button
                        type="button"
                        onClick={() => handleRandomizeBackstory(index)}
                        className="text-[10px] text-amber-400 hover:text-amber-200 flex items-center gap-1 cursor-pointer transition-colors"
                        title="Generate 3-5 sentences of rich fantasy backstory"
                      >
                        <Wand2 className="w-3 h-3" />
                        <span>Gen Backstory</span>
                      </button>
                    </div>
                    <textarea
                      rows={3}
                      value={char.backstory}
                      onChange={(e) => handleUpdateCharacter(index, { backstory: e.target.value })}
                      placeholder="Write or generate a rich fantasy backstory..."
                      className="w-full bg-stone-950 border border-stone-800 rounded-lg px-3 py-2 text-xs text-stone-200 focus:outline-none focus:border-amber-500 resize-none leading-relaxed"
                    />
                  </div>
                </div>
              </div>
            ))}
            </div>
          </div>
        )}

        {/* TAB 2: WORLD SETTING & ATMOSPHERE */}
        {activeTab === 'world' && (
          <div className="space-y-8">
            {/* World Preset Selector */}
            <div className={`bg-stone-900 border rounded-2xl p-6 shadow-xl transition-all ${
              !selectedSettingId ? 'border-amber-500/80 ring-1 ring-amber-500/30' : 'border-stone-800'
            }`}>
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-4">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="text-lg font-serif font-bold text-amber-100 flex items-center gap-2">
                      <Compass className="w-5 h-5 text-amber-400" />
                      Select Campaign Setting & Atmosphere
                    </h3>
                    {!selectedSettingId && (
                      <span className="px-2.5 py-1 rounded-full bg-amber-500 text-stone-950 font-serif font-bold text-xs animate-pulse">
                        Selection Required
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-stone-400">
                    Choose a campaign realm to set the climate, culture, conflict, and mythic atmosphere for your adventure.
                  </p>
                </div>

                {/* Choose Random Scenario Button */}
                <button
                  type="button"
                  onClick={handleSelectRandomScenario}
                  className="px-4 py-2.5 rounded-xl bg-amber-950 hover:bg-amber-900 border border-amber-600/80 text-amber-300 text-xs font-serif font-bold transition-all flex items-center gap-2 cursor-pointer shadow-md hover:scale-105 shrink-0"
                >
                  <Dice5 className="w-4 h-4 text-amber-400 animate-spin" style={{ animationDuration: '6s' }} />
                  <span>Choose Random Scenario</span>
                </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
                {SETTING_PRESETS.map((preset) => (
                  <button
                    key={preset.id}
                    type="button"
                    onClick={() => handleSettingPresetChange(preset.id)}
                    className={`p-5 rounded-xl text-left border transition-all cursor-pointer flex flex-col justify-between ${
                      selectedSettingId === preset.id
                        ? 'bg-amber-950/60 border-amber-500 ring-2 ring-amber-500/50 shadow-xl'
                        : 'bg-stone-950/60 border-stone-800 hover:border-amber-700/60 hover:bg-stone-950'
                    }`}
                  >
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <span className="text-2xl">{preset.bannerEmoji}</span>
                          <span className="font-serif font-bold text-sm text-amber-100">{preset.name}</span>
                        </div>
                        {selectedSettingId === preset.id && (
                          <span className="w-5 h-5 rounded-full bg-amber-500 text-stone-950 flex items-center justify-center font-bold text-xs shrink-0">
                            ✓
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-amber-400 font-medium mb-2 leading-snug">{preset.tagline}</p>
                      <p className="text-xs text-stone-300 leading-relaxed">{preset.description}</p>
                    </div>
                  </button>
                ))}

                <button
                  type="button"
                  onClick={() => handleSettingPresetChange('custom')}
                  className={`p-5 rounded-xl text-left border transition-all cursor-pointer flex flex-col justify-between ${
                    selectedSettingId === 'custom'
                      ? 'bg-amber-950/60 border-amber-500 ring-2 ring-amber-500/50 shadow-xl'
                      : 'bg-stone-950/60 border-stone-800 hover:border-amber-700/60 hover:bg-stone-950'
                  }`}
                >
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <span className="text-2xl">✨</span>
                        <span className="font-serif font-bold text-sm text-amber-100">Custom Homebrew World</span>
                      </div>
                      {selectedSettingId === 'custom' && (
                        <span className="w-5 h-5 rounded-full bg-amber-500 text-stone-950 flex items-center justify-center font-bold text-xs shrink-0">
                          ✓
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-amber-400 font-medium mb-2">Build your own universe concept</p>
                    <p className="text-xs text-stone-300 leading-relaxed">
                      Describe a unique realm, sky kingdom, sunken sea continent, or original fantasy setting.
                    </p>
                  </div>
                </button>
              </div>

              {selectedSettingId === 'custom' && (
                <div className="mb-4">
                  <label className="block text-xs font-serif font-bold text-amber-300 mb-1">
                    Describe Your Custom Campaign Setting:
                  </label>
                  <input
                    type="text"
                    value={customSetting}
                    onChange={(e) => setCustomSetting(e.target.value)}
                    placeholder="e.g., A floating archipelago of shattered sky-islands guarded by storm dragons"
                    className="w-full bg-stone-950 border border-stone-800 rounded-lg px-3 py-2 text-sm text-stone-100 focus:outline-none focus:border-amber-500"
                    required={selectedSettingId === 'custom'}
                  />
                </div>
              )}
            </div>

            {/* Scenario Hook Selector */}
            {selectedSettingId && (
              <div className="bg-stone-900 border border-stone-800 rounded-2xl p-6 shadow-xl animate-fadeIn">
                <h3 className="text-lg font-serif font-bold text-amber-100 mb-2 flex items-center gap-2">
                  <Dice5 className="w-5 h-5 text-amber-400" />
                  Select Initial Scenario Hook
                </h3>
                <p className="text-xs text-stone-400 mb-4">
                  Choose the inciting dilemma that brings your heroes together for this quest.
                </p>

                <div className="space-y-2 mb-4">
                  {SCENARIO_HOOKS.map((hook) => (
                    <label
                      key={hook}
                      className={`flex items-center gap-3 p-3 rounded-xl border transition-colors cursor-pointer ${
                        selectedHook === hook
                          ? 'bg-amber-950/60 border-amber-600 text-amber-100 font-medium'
                          : 'bg-stone-950/50 border-stone-800 text-stone-300 hover:bg-stone-950'
                      }`}
                    >
                      <input
                        type="radio"
                        name="scenarioHook"
                        checked={selectedHook === hook}
                        onChange={() => setSelectedHook(hook)}
                        className="accent-amber-500"
                      />
                      <span className="text-xs">{hook}</span>
                    </label>
                  ))}
                </div>

                {/* Additional Campaign Customization Notes */}
                <div className="pt-2 border-t border-stone-800">
                  <label className="block text-xs font-medium text-stone-400 mb-1">
                    Additional Dungeon Master Notes / Wishes (Optional)
                  </label>
                  <textarea
                    rows={2}
                    value={customNotes}
                    onChange={(e) => setCustomNotes(e.target.value)}
                    placeholder="e.g. Include ancient curses, mysterious dragon cults, or riddle-filled labyrinths..."
                    className="w-full bg-stone-950 border border-stone-800 rounded-lg px-3 py-2 text-xs text-stone-200 focus:outline-none focus:border-amber-500 resize-none"
                  />
                </div>
              </div>
            )}
          </div>
        )}

        {/* Action Controls */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-stone-800">
          {activeTab === 'party' ? (
            <button
              type="button"
              onClick={() => {
                if (validateGenderSelection()) {
                  setActiveTab('world');
                }
              }}
              className={`w-full sm:w-auto px-6 py-3 rounded-xl text-sm font-serif font-bold transition-all flex items-center justify-center gap-2 cursor-pointer ${
                !selectedSettingId
                  ? 'bg-amber-600 text-stone-950 hover:bg-amber-500 shadow-lg animate-bounce'
                  : 'bg-stone-800 hover:bg-stone-700 text-amber-200'
              }`}
            >
              Next: Select World Setting
              <ArrowRight className="w-4 h-4" />
            </button>
          ) : (
            <button
              type="button"
              onClick={() => setActiveTab('party')}
              className="w-full sm:w-auto px-6 py-3 rounded-xl bg-stone-800 hover:bg-stone-700 text-stone-300 text-sm font-medium transition-colors cursor-pointer"
            >
              ← Back to Party Setup
            </button>
          )}

          <div className="flex flex-col items-center sm:items-end gap-1 w-full sm:w-auto">
            <button
              type="submit"
              disabled={isLoading || !selectedSettingId || (selectedSettingId === 'custom' && !customSetting.trim())}
              className={`w-full sm:w-auto px-8 py-4 rounded-xl text-base font-serif font-bold transition-all flex items-center justify-center gap-3 shadow-xl ${
                !selectedSettingId || (selectedSettingId === 'custom' && !customSetting.trim())
                  ? 'bg-stone-800 text-stone-500 border border-stone-700 opacity-60 cursor-not-allowed'
                  : 'bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-500 hover:to-amber-600 text-stone-950 hover:shadow-amber-600/20 cursor-pointer'
              }`}
            >
              {isLoading ? (
                <>
                  <div className="w-5 h-5 border-2 border-stone-950 border-t-transparent rounded-full animate-spin" />
                  Preparing Adventure...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Begin Adventure
                </>
              )}
            </button>
            {!selectedSettingId && (
              <span className="text-[11px] font-mono text-amber-400/90 italic">
                * Please select a world setting to enable 'Begin Adventure'
              </span>
            )}
          </div>
        </div>
      </form>

      {/* Profile Picture Editor Modal */}
      {editingPortraitIndex !== null && party[editingPortraitIndex] && (
        <PortraitEditorModal
          character={party[editingPortraitIndex]}
          isOpen={editingPortraitIndex !== null}
          onClose={() => setEditingPortraitIndex(null)}
          onSavePortrait={(id, newUrl) => {
            handleUpdateCharacter(editingPortraitIndex, { portraitUrl: newUrl });
          }}
        />
      )}
    </div>
  );
};
