import React, { useState } from 'react';
import { Character } from '../types';
import { PRESET_PORTRAITS, getAutoGeneratedPortrait, resizeImageToPortrait } from '../utils/portrait';
import { X, Wand2, Upload, Link, Check, Camera, RefreshCw } from 'lucide-react';
import { soundManager } from '../utils/audio';

interface PortraitEditorModalProps {
  character: Character;
  isOpen: boolean;
  onClose: () => void;
  onSavePortrait: (characterId: string, portraitUrl: string) => void;
}

export const PortraitEditorModal: React.FC<PortraitEditorModalProps> = ({
  character,
  isOpen,
  onClose,
  onSavePortrait,
}) => {
  if (!isOpen) return null;

  const [activeTab, setActiveTab] = useState<'preset' | 'upload' | 'url'>('preset');
  const [selectedUrl, setSelectedUrl] = useState<string>(
    character.portraitUrl || getAutoGeneratedPortrait(character.race, character.characterClass, character.name, character.gender)
  );
  const [customUrl, setCustomUrl] = useState<string>('');
  const [isProcessingFile, setIsProcessingFile] = useState(false);

  const handleSelectPreset = (url: string) => {
    soundManager.playPageTurn();
    setSelectedUrl(url);
  };

  const handleRegenerateAi = () => {
    soundManager.playDiceRoll();
    // Unique seed using timestamp
    const freshSeed = `${character.race}-${character.characterClass}-${character.name}-${Date.now()}`;
    const newPortrait = `https://picsum.photos/seed/${encodeURIComponent(freshSeed)}/512/512`;
    setSelectedUrl(newPortrait);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      setIsProcessingFile(true);
      soundManager.playPageTurn();
      // Silently resizes to 512x512 JPEG with 0.85 quality (~100-150KB)
      const resizedDataUrl = await resizeImageToPortrait(file);
      setSelectedUrl(resizedDataUrl);
    } catch (err) {
      console.error('Error processing portrait image:', err);
    } finally {
      setIsProcessingFile(false);
    }
  };

  const handleApplyCustomUrl = () => {
    if (customUrl.trim()) {
      soundManager.playPageTurn();
      setSelectedUrl(customUrl.trim());
    }
  };

  const handleSave = () => {
    soundManager.playDiceRoll();
    onSavePortrait(character.id, selectedUrl);
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-stone-950/85 backdrop-blur-md z-[60] flex items-center justify-center p-4">
      <div className="bg-stone-900 border border-amber-800/60 rounded-2xl max-w-lg w-full p-6 shadow-2xl text-stone-100 relative max-h-[90vh] overflow-y-auto">
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 text-stone-400 hover:text-amber-200 rounded-lg hover:bg-stone-800 transition-colors cursor-pointer"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-stone-800 pb-4 mb-5">
          <Camera className="w-6 h-6 text-amber-400" />
          <div>
            <h3 className="text-xl font-serif font-bold text-amber-100">
              Edit Hero Portrait
            </h3>
            <p className="text-xs text-stone-400">
              Customize profile picture for {character.name} ({character.race} {character.characterClass})
            </p>
          </div>
        </div>

        {/* Main Preview */}
        <div className="flex flex-col sm:flex-row items-center gap-4 bg-stone-950 p-4 rounded-xl border border-stone-800 mb-5">
          <div className="relative group">
            <img
              src={selectedUrl}
              alt={character.name}
              referrerPolicy="no-referrer"
              className="w-28 h-28 rounded-xl object-cover border-2 border-amber-500/80 shadow-lg bg-stone-900"
            />
            <div className="absolute -bottom-2 -right-2 bg-amber-500 text-stone-950 p-1 rounded-full shadow">
              <Check className="w-3.5 h-3.5" />
            </div>
          </div>

          <div className="flex-1 text-center sm:text-left space-y-2">
            <h4 className="font-bold text-amber-200 text-sm">{character.name}</h4>
            <p className="text-xs text-stone-400">
              Level {character.level} {character.race} {character.characterClass}
            </p>
            <button
              type="button"
              onClick={handleRegenerateAi}
              className="px-3 py-1.5 bg-amber-950 hover:bg-amber-900 text-amber-200 border border-amber-800 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 mx-auto sm:mx-0 cursor-pointer shadow-sm"
            >
              <RefreshCw className="w-3.5 h-3.5 text-amber-400" />
              <span>Auto-Generate Portrait</span>
            </button>
          </div>
        </div>

        {/* Tab Selection */}
        <div className="flex border-b border-stone-800 mb-4">
          <button
            type="button"
            onClick={() => setActiveTab('preset')}
            className={`flex-1 py-2 text-xs font-bold font-serif transition-colors border-b-2 cursor-pointer ${
              activeTab === 'preset'
                ? 'border-amber-500 text-amber-300'
                : 'border-transparent text-stone-400 hover:text-stone-200'
            }`}
          >
            Fantasy Gallery
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('upload')}
            className={`flex-1 py-2 text-xs font-bold font-serif transition-colors border-b-2 cursor-pointer ${
              activeTab === 'upload'
                ? 'border-amber-500 text-amber-300'
                : 'border-transparent text-stone-400 hover:text-stone-200'
            }`}
          >
            Upload File
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('url')}
            className={`flex-1 py-2 text-xs font-bold font-serif transition-colors border-b-2 cursor-pointer ${
              activeTab === 'url'
                ? 'border-amber-500 text-amber-300'
                : 'border-transparent text-stone-400 hover:text-stone-200'
            }`}
          >
            Paste Image URL
          </button>
        </div>

        {/* Tab Contents */}
        {activeTab === 'preset' && (
          <div className="space-y-3">
            <p className="text-xs text-stone-400">
              Select a fantasy portrait style from the library:
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 max-h-56 overflow-y-auto p-1">
              {PRESET_PORTRAITS.map((p) => {
                const isSelected = selectedUrl === p.url;
                return (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => handleSelectPreset(p.url)}
                    className={`p-1.5 rounded-xl border text-left transition-all cursor-pointer relative group ${
                      isSelected
                        ? 'border-amber-400 bg-amber-950/60 ring-2 ring-amber-500/50 scale-105'
                        : 'border-stone-800 bg-stone-950 hover:border-stone-700'
                    }`}
                  >
                    <img
                      src={p.url}
                      alt={p.label}
                      referrerPolicy="no-referrer"
                      className="w-full h-20 object-cover rounded-lg mb-1"
                    />
                    <div className="text-[10px] font-bold text-stone-200 truncate">
                      {p.label}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {activeTab === 'upload' && (
          <div className="space-y-4 py-2">
            <p className="text-xs text-stone-400">
              Choose an image file from your device:
            </p>
            <label className="border-2 border-dashed border-stone-700 hover:border-amber-500 rounded-xl p-6 flex flex-col items-center justify-center gap-2 cursor-pointer bg-stone-950/60 transition-colors">
              <Upload className="w-8 h-8 text-amber-400" />
              <span className="text-xs font-bold text-stone-200">
                {isProcessingFile ? 'Processing image...' : 'Click to Browse Local Image'}
              </span>
              <input
                type="file"
                accept="image/*"
                onChange={handleFileUpload}
                disabled={isProcessingFile}
                className="hidden"
              />
            </label>
          </div>
        )}

        {activeTab === 'url' && (
          <div className="space-y-3 py-2">
            <p className="text-xs text-stone-400">
              Paste a direct image link from the web:
            </p>
            <div className="flex gap-2">
              <input
                type="url"
                value={customUrl}
                onChange={(e) => setCustomUrl(e.target.value)}
                placeholder="https://example.com/portrait.jpg"
                className="flex-1 bg-stone-950 border border-stone-800 rounded-xl px-3 py-2 text-xs text-stone-100 focus:outline-none focus:border-amber-500 font-mono"
              />
              <button
                type="button"
                onClick={handleApplyCustomUrl}
                className="px-3 py-2 bg-amber-600 hover:bg-amber-500 text-stone-950 rounded-xl text-xs font-bold transition-all cursor-pointer"
              >
                Apply
              </button>
            </div>
          </div>
        )}

        {/* Footer Actions */}
        <div className="flex items-center justify-end gap-3 mt-6 pt-4 border-t border-stone-800">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 bg-stone-800 hover:bg-stone-700 text-stone-300 rounded-xl text-xs font-bold transition-all cursor-pointer"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSave}
            className="px-5 py-2 bg-amber-500 hover:bg-amber-400 text-stone-950 rounded-xl text-xs font-bold transition-all cursor-pointer shadow-lg shadow-amber-500/20"
          >
            Save Profile Picture
          </button>
        </div>
      </div>
    </div>
  );
};
