import React, { useState } from 'react';
import { Character } from '../types';
import { PRESET_PORTRAITS, getAutoGeneratedPortrait, resizeImageToPortrait, PresetPortraitOption } from '../utils/portrait';
import { X, Wand2, Upload, Link, Check, Camera, RefreshCw, Filter, Sparkles } from 'lucide-react';
import { soundManager } from '../utils/audio';

interface PortraitEditorModalProps {
  character: Character;
  isOpen: boolean;
  onClose: () => void;
  onSavePortrait: (characterId: string, portraitUrl: string) => void;
}

export const PortraitEditorModal: React.FC<PortraitEditorModalProps> = ({
  character,
  isOpen,
  onClose,
  onSavePortrait,
}) => {
  if (!isOpen) return null;

  const [activeTab, setActiveTab] = useState<'preset' | 'upload' | 'url'>('preset');
  const [selectedUrl, setSelectedUrl] = useState<string>(
    character.portraitUrl || getAutoGeneratedPortrait(character.race, character.characterClass, character.name, character.gender)
  );
  const [genderFilter, setGenderFilter] = useState<'all' | 'male' | 'female'>(
    character.gender === 'Female' ? 'female' : character.gender === 'Male' ? 'male' : 'all'
  );
  const [categoryFilter, setCategoryFilter] = useState<string>('All');
  const [customUrl, setCustomUrl] = useState<string>('');
  const [isProcessingFile, setIsProcessingFile] = useState(false);

  const handleSelectPreset = (url: string) => {
    soundManager.playPageTurn();
    setSelectedUrl(url);
  };

  const handleResetToAuto = () => {
    soundManager.playDiceRoll();
    const auto = getAutoGeneratedPortrait(character.race, character.characterClass, character.name, character.gender);
    setSelectedUrl(auto);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      setIsProcessingFile(true);
      soundManager.playPageTurn();
      // Silently resizes to 512x512 JPEG with 0.85 quality (~100-150KB)
      const resizedDataUrl = await resizeImageToPortrait(file);
      setSelectedUrl(resizedDataUrl);
    } catch (err) {
      console.error('Error processing portrait image:', err);
    } finally {
      setIsProcessingFile(false);
    }
  };

  const handleApplyCustomUrl = () => {
    if (customUrl.trim()) {
      soundManager.playPageTurn();
      setSelectedUrl(customUrl.trim());
    }
  };

  const handleSave = () => {
    soundManager.playDiceRoll();
    onSavePortrait(character.id, selectedUrl);
    onClose();
  };

  const filteredPresets = PRESET_PORTRAITS.filter((p) => {
    if (genderFilter !== 'all' && p.gender !== genderFilter) return false;
    if (categoryFilter !== 'All' && p.category !== categoryFilter) return false;
    return true;
  });

  return (
    <div className="fixed inset-0 bg-stone-950/85 backdrop-blur-md z-[60] flex items-center justify-center p-4">
      <div className="bg-stone-900 border border-amber-800/60 rounded-2xl max-w-xl w-full p-6 shadow-2xl text-stone-100 relative max-h-[90vh] overflow-y-auto">
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 text-stone-400 hover:text-amber-200 rounded-lg hover:bg-stone-800 transition-colors cursor-pointer"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-stone-800 pb-4 mb-5">
          <Camera className="w-6 h-6 text-amber-400" />
          <div>
            <h3 className="text-xl font-serif font-bold text-amber-100">
              Edit Hero Portrait
            </h3>
            <p className="text-xs text-stone-400">
              Customize profile picture for {character.name} ({character.race} {character.characterClass})
            </p>
          </div>
        </div>

        {/* Main Current Selection Preview */}
        <div className="flex flex-col sm:flex-row items-center gap-4 bg-stone-950 p-4 rounded-xl border border-stone-800 mb-5">
          <div className="relative group">
            <img
              src={selectedUrl}
              alt={character.name}
              referrerPolicy="no-referrer"
              className="w-24 h-24 sm:w-28 sm:h-28 rounded-xl object-cover border-2 border-amber-500/80 shadow-lg bg-stone-900"
            />
            <div className="absolute -bottom-2 -right-2 bg-amber-500 text-stone-950 p-1 rounded-full shadow">
              <Check className="w-3.5 h-3.5" />
            </div>
          </div>

          <div className="flex-1 text-center sm:text-left space-y-2">
            <h4 className="font-bold text-amber-200 text-sm">{character.name}</h4>
            <p className="text-xs text-stone-400">
              Level {character.level} {character.race} {character.characterClass} {character.gender ? `(${character.gender})` : ''}
            </p>
            <button
              type="button"
              onClick={handleResetToAuto}
              className="px-3 py-1.5 bg-amber-950/80 hover:bg-amber-900 text-amber-200 border border-amber-800/80 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 mx-auto sm:mx-0 cursor-pointer shadow-sm"
            >
              <RefreshCw className="w-3.5 h-3.5 text-amber-400" />
              <span>Reset to Class Default</span>
            </button>
          </div>
        </div>

        {/* Tab Selection */}
        <div className="flex border-b border-stone-800 mb-4">
          <button
            type="button"
            onClick={() => setActiveTab('preset')}
            className={`flex-1 py-2 text-xs font-bold font-serif transition-colors border-b-2 cursor-pointer ${
              activeTab === 'preset'
                ? 'border-amber-500 text-amber-300'
                : 'border-transparent text-stone-400 hover:text-stone-200'
            }`}
          >
            Fantasy Artwork Gallery ({PRESET_PORTRAITS.length})
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('upload')}
            className={`flex-1 py-2 text-xs font-bold font-serif transition-colors border-b-2 cursor-pointer ${
              activeTab === 'upload'
                ? 'border-amber-500 text-amber-300'
                : 'border-transparent text-stone-400 hover:text-stone-200'
            }`}
          >
            Upload File
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('url')}
            className={`flex-1 py-2 text-xs font-bold font-serif transition-colors border-b-2 cursor-pointer ${
              activeTab === 'url'
                ? 'border-amber-500 text-amber-300'
                : 'border-transparent text-stone-400 hover:text-stone-200'
            }`}
          >
            Paste Image URL
          </button>
        </div>

        {/* Tab Contents */}
        {activeTab === 'preset' && (
          <div className="space-y-3">
            {/* Filters Bar */}
            <div className="flex flex-wrap items-center justify-between gap-2 bg-stone-950 p-2.5 rounded-xl border border-stone-800 text-xs">
              {/* Gender Filter */}
              <div className="flex items-center gap-1">
                <span className="text-[11px] font-bold text-stone-400 mr-1">Gender:</span>
                {(['all', 'male', 'female'] as const).map((g) => (
                  <button
                    key={g}
                    type="button"
                    onClick={() => setGenderFilter(g)}
                    className={`px-2 py-0.5 rounded capitalize text-[11px] font-bold cursor-pointer transition-all ${
                      genderFilter === g
                        ? 'bg-amber-500 text-stone-950 shadow'
                        : 'bg-stone-900 text-stone-400 hover:text-stone-200 border border-stone-800'
                    }`}
                  >
                    {g}
                  </button>
                ))}
              </div>

              {/* Archetype / Category Filter */}
              <div className="flex items-center gap-1">
                <span className="text-[11px] font-bold text-stone-400 mr-1">Category:</span>
                <select
                  value={categoryFilter}
                  onChange={(e) => setCategoryFilter(e.target.value)}
                  className="bg-stone-900 border border-stone-700 text-amber-200 rounded px-2 py-0.5 text-[11px] focus:outline-none focus:border-amber-500"
                >
                  <option value="All">All Roles</option>
                  <option value="Martial">Martial (Fighter/Barbarian)</option>
                  <option value="Arcane">Arcane (Wizard/Warlock/Bard)</option>
                  <option value="Divine">Divine (Cleric)</option>
                  <option value="Nature">Nature (Druid)</option>
                  <option value="Stealth">Stealth (Rogue)</option>
                  <option value="Adventurer">Adventurer</option>
                </select>
              </div>
            </div>

            {/* Portraits Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5 max-h-64 overflow-y-auto p-1">
              {filteredPresets.map((p) => {
                const isSelected = selectedUrl === p.url;
                const isMatchingClass = p.classMatch === character.characterClass;
                return (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => handleSelectPreset(p.url)}
                    className={`p-1.5 rounded-xl border text-left transition-all cursor-pointer relative group flex flex-col items-center ${
                      isSelected
                        ? 'border-amber-400 bg-amber-950/70 ring-2 ring-amber-500/50 scale-[1.02]'
                        : 'border-stone-800 bg-stone-950 hover:border-stone-700'
                    }`}
                  >
                    <div className="relative w-full aspect-square mb-1.5 overflow-hidden rounded-lg">
                      <img
                        src={p.url}
                        alt={p.label}
                        referrerPolicy="no-referrer"
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                      />
                      {isMatchingClass && (
                        <span className="absolute top-1 left-1 bg-amber-500/90 text-stone-950 text-[9px] font-bold px-1.5 py-0.5 rounded shadow">
                          Class Match
                        </span>
                      )}
                      {isSelected && (
                        <div className="absolute inset-0 bg-amber-500/20 flex items-center justify-center">
                          <Check className="w-6 h-6 text-amber-300 drop-shadow-md" />
                        </div>
                      )}
                    </div>
                    <div className="w-full text-center">
                      <div className="text-[11px] font-bold text-stone-200 truncate">
                        {p.label}
                      </div>
                      <div className="text-[9px] text-amber-400/80 capitalize">
                        {p.category} • {p.gender}
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {activeTab === 'upload' && (
          <div className="space-y-4 py-2">
            <p className="text-xs text-stone-400">
              Choose a custom image file from your device:
            </p>
            <label className="border-2 border-dashed border-stone-700 hover:border-amber-500 rounded-xl p-6 flex flex-col items-center justify-center gap-2 cursor-pointer bg-stone-950/60 transition-colors">
              <Upload className="w-8 h-8 text-amber-400" />
              <span className="text-xs font-bold text-stone-200">
                {isProcessingFile ? 'Processing image...' : 'Click to Browse Local Image'}
              </span>
              <span className="text-[10px] text-stone-400">Auto-cropped and optimized for fast display</span>
              <input
                type="file"
                accept="image/*"
                onChange={handleFileUpload}
                disabled={isProcessingFile}
                className="hidden"
              />
            </label>
          </div>
        )}

        {activeTab === 'url' && (
          <div className="space-y-3 py-2">
            <p className="text-xs text-stone-400">
              Paste a direct image link from the web:
            </p>
            <div className="flex gap-2">
              <input
                type="url"
                value={customUrl}
                onChange={(e) => setCustomUrl(e.target.value)}
                placeholder="https://example.com/portrait.jpg"
                className="flex-1 bg-stone-950 border border-stone-800 rounded-xl px-3 py-2 text-xs text-stone-100 focus:outline-none focus:border-amber-500 font-mono"
              />
              <button
                type="button"
                onClick={handleApplyCustomUrl}
                className="px-3 py-2 bg-amber-600 hover:bg-amber-500 text-stone-950 rounded-xl text-xs font-bold transition-all cursor-pointer"
              >
                Apply
              </button>
            </div>
          </div>
        )}

        {/* Footer Actions */}
        <div className="flex items-center justify-end gap-3 mt-6 pt-4 border-t border-stone-800">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 bg-stone-800 hover:bg-stone-700 text-stone-300 rounded-xl text-xs font-bold transition-all cursor-pointer"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSave}
            className="px-5 py-2 bg-amber-500 hover:bg-amber-400 text-stone-950 rounded-xl text-xs font-bold transition-all cursor-pointer shadow-lg shadow-amber-500/20"
          >
            Save Profile Picture
          </button>
        </div>
      </div>
    </div>
  );
};

