import { CharacterClass, Race, Gender } from '../types';
import fighterPortrait from '../assets/images/fighter_portrait_1786405685026.jpg';
import wizardPortrait from '../assets/images/wizard_portrait_1786405696063.jpg';
import roguePortrait from '../assets/images/rogue_portrait_1786405706145.jpg';

export interface PresetPortraitOption {
  id: string;
  label: string;
  url: string;
  category: string;
}

export const PRESET_PORTRAITS: PresetPortraitOption[] = [
  {
    id: 'fighter-gen',
    label: 'Heroic Fighter / Paladin',
    url: fighterPortrait,
    category: 'Martial',
  },
  {
    id: 'wizard-gen',
    label: 'Arcane Wizard / Sorcerer',
    url: wizardPortrait,
    category: 'Arcane',
  },
  {
    id: 'rogue-gen',
    label: 'Shadow Rogue / Ranger',
    url: roguePortrait,
    category: 'Stealth',
  },
  {
    id: 'cleric-divine',
    label: 'Divine Cleric / Paladin',
    url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=512&auto=format&fit=crop&q=80',
    category: 'Divine',
  },
  {
    id: 'druid-nature',
    label: 'Wild Druid / Ranger',
    url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=512&auto=format&fit=crop&q=80',
    category: 'Nature',
  },
  {
    id: 'warlock-dark',
    label: 'Eldritch Warlock / Tiefling',
    url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=512&auto=format&fit=crop&q=80',
    category: 'Eldritch',
  },
  {
    id: 'barbarian-rage',
    label: 'Fierce Barbarian / Half-Orc',
    url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=512&auto=format&fit=crop&q=80',
    category: 'Martial',
  },
  {
    id: 'bard-mystic',
    label: 'Charismatic Bard / Gnome',
    url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=512&auto=format&fit=crop&q=80',
    category: 'Arcane',
  },
];

/**
 * Auto-generates a high-quality character profile picture based on race, class, and name seed.
 */
export function getAutoGeneratedPortrait(
  race: Race,
  characterClass: CharacterClass,
  name: string = 'Hero',
  gender?: Gender
): string {
  // If matching our primary generated image assets
  if (['Fighter', 'Paladin', 'Barbarian'].includes(characterClass)) {
    return fighterPortrait;
  }
  if (['Wizard', 'Sorcerer', 'Warlock', 'Cleric'].includes(characterClass)) {
    return wizardPortrait;
  }
  if (['Rogue', 'Ranger', 'Monk', 'Bard', 'Druid'].includes(characterClass)) {
    return roguePortrait;
  }

  // Fallback seed URL (512x512 px)
  const seed = encodeURIComponent(`${race}-${characterClass}-${gender || 'hero'}-${name}`);
  return `https://picsum.photos/seed/${seed}/512/512`;
}

/**
 * Resizes an uploaded image file using HTML5 Canvas to 512x512 pixels
 * compressed as JPEG (quality 0.85) to target ~100-150KB optimal profile picture size.
 */
export function resizeImageToPortrait(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    if (!file.type.startsWith('image/')) {
      reject(new Error('Selected file is not an image.'));
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const TARGET_SIZE = 512; // 512x512 square profile picture
        canvas.width = TARGET_SIZE;
        canvas.height = TARGET_SIZE;

        const ctx = canvas.getContext('2d');
        if (!ctx) {
          reject(new Error('Failed to create canvas context'));
          return;
        }

        // Calculate aspect fill crop
        const minDim = Math.min(img.width, img.height);
        const sx = (img.width - minDim) / 2;
        const sy = (img.height - minDim) / 2;

        ctx.drawImage(img, sx, sy, minDim, minDim, 0, 0, TARGET_SIZE, TARGET_SIZE);

        // Compress as JPEG at 85% quality (~100-150KB file size)
        const dataUrl = canvas.toDataURL('image/jpeg', 0.85);
        resolve(dataUrl);
      };
      img.onerror = () => reject(new Error('Failed to load image file.'));
      img.src = e.target?.result as string;
    };
    reader.onerror = () => reject(new Error('Failed to read image file.'));
    reader.readAsDataURL(file);
  });
}
