import { Character, CharacterClass, Race, Stats, Gender, StatusEffectType } from '../types';
import { getAutoGeneratedPortrait } from '../utils/portrait';

export interface SettingPreset {
  id: string;
  name: string;
  tagline: string;
  description: string;
  wikiTopics: string[];
  bannerEmoji: string;
  defaultHook: string;
}

export const SETTING_PRESETS: SettingPreset[] = [
  {
    id: 'bronze-empire',
    name: 'The Sunken Aegean & Minoan Citadel',
    tagline: 'Bronze Age myth, labyrinthine coastal ruins, and ancient sea leagues',
    description:
      'Inspired by Bronze Age Minoan maritime trade, Mycenaean fortress palaces, and ancient Mediterranean mythology. Copper-clad warriors and tide-whisperers navigate sunken coastal labyrinths.',
    wikiTopics: ['Minoan civilization', 'Linear B', 'Mycenaean Greece', 'Sea Peoples', 'Bronze Age collapse'],
    bannerEmoji: '🏛️',
    defaultHook: 'An ancient bronze seal uncovered in a subterranean sea cave holds the key to a lost sunken vault.',
  },
  {
    id: 'gothic-teutonic',
    name: 'The Black Forest & Feudal Keep',
    tagline: 'Gothic chivalry, deep haunted pine woods, and Teutonic strongholds',
    description:
      'Draws inspiration from High Middle Ages Germanic keeps, the Black Forest, Teutonic knightly orders, and medieval feudal rivalries.',
    wikiTopics: ['Teutonic Order', 'Black Forest', 'Gothic architecture', 'Holy Roman Empire', 'Feudalism'],
    bannerEmoji: '🏰',
    defaultHook: 'A dark corruption creeps from the ancient pine woods, surrounding an isolated borderland keep.',
  },
  {
    id: 'silk-road',
    name: 'The Oasis Leagues & Silk Route',
    tagline: 'Sogdian trade caravans, desert citadels, and ancient mountain passes',
    description:
      'Inspired by the historical Silk Road caravans, Sogdian merchants, Tang Dynasty outposts, and high-desert oasis kingdoms.',
    wikiTopics: ['Silk Road', 'Sogdia', 'Dunhuang', 'Caravanserai', 'Tang dynasty'],
    bannerEmoji: '🏜️',
    defaultHook: 'A priceless relic disappeared from a guarded caravanserai amidst an approaching sandstorm.',
  },
  {
    id: 'steppe-horde',
    name: 'The High Steppes & Nomadic Sagas',
    tagline: 'Scythian horseback archers, ancient burial mounds, and spirit shamans',
    description:
      'Modelled after Scythian and Eurasian nomadic cultures, ancient kurgan burial mounds, horseback archers, and ancestral spirit traditions.',
    wikiTopics: ['Scythians', 'Kurgan', 'Eurasian Steppe', 'Tengrism', 'Nomad'],
    bannerEmoji: '🐎',
    defaultHook: 'Ancestral spirits cry out as grave robbers desecrate a holy kurgan mound on the open plains.',
  },
  {
    id: 'sun-citadel',
    name: 'The Sun-Temple Citadels & High Peaks',
    tagline: 'Inca mountain engineering, Mesoamerican solar temples, and cloud ruins',
    description:
      'Inspired by Andean Inca terrace engineering, Machu Picchu, and Mesoamerican solar calendar temples set high above the cloud forest.',
    wikiTopics: ['Inca Empire', 'Machu Picchu', 'Mesoamerica', 'Andean civilizations', 'Solar calendar'],
    bannerEmoji: '🏔️',
    defaultHook: 'The solar altar at the high peak has gone cold, threatening an eternal eclipse across the valleys.',
  },
];

export const SCENARIO_HOOKS = [
  'An ancient artifact unearthed in a collapsed mountain crypt',
  'A high-stakes escort mission through contested borderlands',
  'Investigating an eldritch plague corrupting the regional trade routes',
  'A royal assassination conspiracy inside the Grand Merchant Republic',
  'An expedition into a newly uncovered sunken labyrinth below the coastal cliffs',
];

export const WIKIPEDIA_INSPIRATION_PRESETS = [
  'Minoan civilization',
  'Teutonic Order',
  'Silk Road',
  'Scythians',
  'Inca Empire',
  'Byzantine Empire',
  'Celtic mythology',
  'Phoenicia',
  'Varangian Guard',
  'Songhai Empire',
  'Samurai',
  'Norse sagas',
];

export function getStatModifier(statValue: number): number {
  return Math.floor((statValue - 10) / 2);
}

export function formatModifier(mod: number): string {
  return mod >= 0 ? `+${mod}` : `${mod}`;
}

export const ALL_CLASSES: CharacterClass[] = [
  'Fighter',
  'Wizard',
  'Rogue',
  'Cleric',
  'Paladin',
  'Barbarian',
  'Bard',
  'Ranger',
  'Warlock',
  'Sorcerer',
  'Druid',
  'Monk',
];

export const ALL_RACES: Race[] = [
  'Human',
  'Elf',
  'Dwarf',
  'Halfling',
  'Tiefling',
  'Dragonborn',
  'Half-Orc',
  'Gnome',
];

/** Standard D&D 5E stat roll rule: Roll 4d6 and drop the lowest die value */
export function roll4d6DropLowest(): number {
  const rolls = [
    Math.floor(Math.random() * 6) + 1,
    Math.floor(Math.random() * 6) + 1,
    Math.floor(Math.random() * 6) + 1,
    Math.floor(Math.random() * 6) + 1,
  ];
  rolls.sort((a, b) => a - b);
  return rolls[1] + rolls[2] + rolls[3];
}

export function rollDndStats(): Stats {
  return {
    str: roll4d6DropLowest(),
    dex: roll4d6DropLowest(),
    con: roll4d6DropLowest(),
    int: roll4d6DropLowest(),
    wis: roll4d6DropLowest(),
    cha: roll4d6DropLowest(),
  };
}

const NAME_POOL: Record<Race, string[]> = {
  Human: ['Valerius', 'Garrick', 'Caelen', 'Helena', 'Brunhild', 'Rowan', 'Cassian', 'Mirella', 'Eamon', 'Thorne', 'Alistair', 'Corvus', 'Seraphina', 'Doran', 'Genevieve'],
  Elf: ['Eldrin', 'Lyra', 'Sylvan', 'Aurelia', 'Vaelin', 'Faelar', 'Sylphira', 'Theron', 'Elion', 'Caelynn', 'Aerin', 'Lathandra', 'Ilphrin', 'Valeria', 'Thorniel'],
  Dwarf: ['Thorin', 'Brak', 'Gloin', 'Hilda', 'Orla', 'Dagmar', 'Kargan', 'Rurik', 'Brakka', 'Eldrid', 'Balthasar', 'Grimjaw', 'Kaelen', 'Ulfgar', 'Vondal'],
  Halfling: ['Pip', 'Rosie', 'Callum', 'Milo', 'Talia', 'Cora', 'Oswald', 'Penny', 'Barnaby', 'Merry', 'Alton', 'Bree', 'Finnan', 'Lavinia', 'Pippin'],
  Tiefling: ['Nyx', 'Malakor', 'Morrigan', 'Zarek', 'Vesper', 'Kassandra', 'Lucian', 'Ignis', 'Riven', 'Azreal', 'Damien', 'Lilith', 'Kharon', 'Xerxes', 'Mephista'],
  Dragonborn: ['Balthazar', 'Kaelen', 'Thorgar', 'Zephyr', 'Rhaegar', 'Ignatia', 'Drakon', 'Vespera', 'Khorag', 'Pyra', 'Arjhan', 'Bharash', 'Drakar', 'Kriv', 'Medrash'],
  'Half-Orc': ['Grendel', 'Brak', 'Garr', 'Karg', 'Rhaena', 'Morgar', 'Skandar', 'Varn', 'Urgash', 'Kull', 'Dench', 'Feng', 'Gell', 'Krag', 'Ront'],
  Gnome: ['Fizzle', 'Ziggy', 'Lotus', 'Bramble', 'Tink', 'Nobby', 'Pippin', 'Zinnia', 'Wrenn', 'Quigley', 'Boddynock', 'Dimble', 'Fonkin', 'Gimble', 'Namfoodle'],
};

export function generateRandomName(
  characterClass: CharacterClass,
  race: Race,
  existingNames: string[] = []
): string {
  const pool = NAME_POOL[race] || NAME_POOL.Human;
  const lowerExisting = existingNames.map((n) => n.trim().toLowerCase());

  // Filter pool for unused names
  const available = pool.filter((n) => !lowerExisting.includes(n.toLowerCase()));
  if (available.length > 0) {
    return available[Math.floor(Math.random() * available.length)];
  }

  // If pool runs low, append unique title/surname
  const epithets = ['Stormweaver', 'Ironhand', 'Shadowwalker', 'the Bold', 'Lightbringer', 'Vanguard', 'Spellweaver', 'Shieldbearer', 'the Brave', 'Frostblade', 'the Undaunted', 'Starcaller'];
  for (let i = 0; i < 50; i++) {
    const base = pool[Math.floor(Math.random() * pool.length)];
    const ep = epithets[Math.floor(Math.random() * epithets.length)];
    const candidate = `${base} ${ep}`;
    if (!lowerExisting.includes(candidate.toLowerCase())) {
      return candidate;
    }
  }

  return `${pool[0]} ${Math.floor(Math.random() * 900 + 100)}`;
}

export interface StatusEffectConfig {
  type: StatusEffectType;
  emoji: string;
  label: string;
  description: string;
  bgClass: string;
  textClass: string;
  borderClass: string;
  iconName: string;
}

export const ALL_STATUS_EFFECTS: StatusEffectType[] = [
  'Poisoned',
  'Stunned',
  'Inspired',
  'Blessed',
  'Charmed',
  'Blinded',
  'Frightened',
  'Restrained',
  'Hasted',
  'Shielded',
];

export const STATUS_EFFECTS_CONFIG: Record<StatusEffectType, StatusEffectConfig> = {
  Poisoned: {
    type: 'Poisoned',
    emoji: '🧪',
    label: 'Poisoned',
    description: 'Disadvantage on attack rolls and ability checks from toxins.',
    bgClass: 'bg-emerald-950/90',
    textClass: 'text-emerald-300',
    borderClass: 'border-emerald-700/80',
    iconName: 'Biohazard',
  },
  Stunned: {
    type: 'Stunned',
    emoji: '⚡',
    label: 'Stunned',
    description: 'Incapacitated, unable to move, and fails STR/DEX saving throws.',
    bgClass: 'bg-yellow-950/90',
    textClass: 'text-yellow-300',
    borderClass: 'border-yellow-600/80',
    iconName: 'Zap',
  },
  Inspired: {
    type: 'Inspired',
    emoji: '✨',
    label: 'Inspired',
    description: 'Heroic motivation! Can gain advantage on an attack, save, or check.',
    bgClass: 'bg-amber-950/90',
    textClass: 'text-amber-200',
    borderClass: 'border-amber-500/90',
    iconName: 'Sparkles',
  },
  Blessed: {
    type: 'Blessed',
    emoji: '🛡️',
    label: 'Blessed',
    description: 'Divine favor granting +1d4 bonus to attack rolls and saving throws.',
    bgClass: 'bg-cyan-950/90',
    textClass: 'text-cyan-300',
    borderClass: 'border-cyan-600/80',
    iconName: 'Sun',
  },
  Charmed: {
    type: 'Charmed',
    emoji: '💖',
    label: 'Charmed',
    description: 'Cannot attack the charmer; charmer has advantage on social interactions.',
    bgClass: 'bg-rose-950/90',
    textClass: 'text-rose-300',
    borderClass: 'border-rose-600/80',
    iconName: 'Heart',
  },
  Blinded: {
    type: 'Blinded',
    emoji: '👁️',
    label: 'Blinded',
    description: 'Cannot see; attack rolls against hero have advantage, hero attacks have disadvantage.',
    bgClass: 'bg-stone-900',
    textClass: 'text-purple-300',
    borderClass: 'border-purple-800/80',
    iconName: 'EyeOff',
  },
  Frightened: {
    type: 'Frightened',
    emoji: '😱',
    label: 'Frightened',
    description: 'Disadvantage on ability checks and attack rolls while source of fear is in sight.',
    bgClass: 'bg-violet-950/90',
    textClass: 'text-violet-300',
    borderClass: 'border-violet-700/80',
    iconName: 'AlertTriangle',
  },
  Restrained: {
    type: 'Restrained',
    emoji: '⛓️',
    label: 'Restrained',
    description: 'Speed 0; attacks against hero have advantage, hero attacks have disadvantage.',
    bgClass: 'bg-orange-950/90',
    textClass: 'text-orange-300',
    borderClass: 'border-orange-700/80',
    iconName: 'Lock',
  },
  Hasted: {
    type: 'Hasted',
    emoji: '🏃',
    label: 'Hasted',
    description: 'Doubled speed, +2 AC, advantage on DEX saves, plus an additional action.',
    bgClass: 'bg-teal-950/90',
    textClass: 'text-teal-300',
    borderClass: 'border-teal-600/80',
    iconName: 'Gauge',
  },
  Shielded: {
    type: 'Shielded',
    emoji: '🛡️',
    label: 'Shielded',
    description: 'Arcane magical barrier granting +5 AC or warding against damage.',
    bgClass: 'bg-blue-950/90',
    textClass: 'text-blue-300',
    borderClass: 'border-blue-600/80',
    iconName: 'ShieldCheck',
  },
};

export function getPronouns(gender?: Gender) {
  if (gender === 'Male') {
    return {
      subject: 'he',
      Subject: 'He',
      object: 'him',
      possessive: 'his',
      Possessive: 'His',
      possessiveAdj: 'his',
      reflexive: 'himself',
    };
  }
  if (gender === 'Female') {
    return {
      subject: 'she',
      Subject: 'She',
      object: 'her',
      possessive: 'hers',
      Possessive: 'Hers',
      possessiveAdj: 'her',
      reflexive: 'herself',
    };
  }
  return {
    subject: 'they',
    Subject: 'They',
    object: 'them',
    possessive: 'theirs',
    Possessive: 'Their',
    possessiveAdj: 'their',
    reflexive: 'themselves',
  };
}

/** Generates a high-quality, guaranteed unique 3-5 sentence fantasy backstory based on class, race, name, and gender pronouns */
export function generateFantasyBackstory(
  name: string,
  race: Race,
  characterClass: CharacterClass,
  existingBackstories: string[] = [],
  gender: Gender = "I'd rather not say"
): string {
  const p = getPronouns(gender);
  const lowerExisting = existingBackstories.map((b) => b.trim().toLowerCase());

  const origins = [
    `Raised in the mist-shrouded borderlands of the ancient realms, ${name} inherited the unyielding resilience of ${p.possessiveAdj} ${race} lineage.`,
    `Hailing from the high spires of an elder citadel, ${name} was steeped in the solemn traditions and forgotten lore of the ${race} elders.`,
    `Schooled in the perilous frontier outposts where civilization fades into wild myth, ${name} learned early that a ${race}'s sharp instincts mean the difference between life and death.`,
    `Born under a blood-red moon during a fierce mountain siege, ${name} carried the mark of destiny long before taking up arms as a ${characterClass}.`,
    `Trained in secret sanctuaries nestled deep within the primordial forests, ${name} earned a revered place among ${p.possessiveAdj} ${race} clan.`,
    `Abandoned as an infant near the whispering ruins of an ancient arcane temple, ${name} was fostered by veteran ${race} guardians.`,
    `Growing up in the bustling harbor districts of a coastal metropolis, ${name} developed a razor-sharp survival instinct and a thirst for high adventure.`,
    `Deep in the subterranean caverns where light never penetrates, ${name} forged ${p.possessiveAdj} willpower amidst molten stone and dark magic.`,
  ];

  const turningPoints = [
    `When an ancient shadow shattered the tranquility of ${p.possessiveAdj} homeland, ${name} pledged ${p.possessiveAdj} weapon as a ${characterClass} to defend the helpless.`,
    `After discovering a cryptic heirloom inscribed with forbidden runes, ${name} embarked on a quest to uncover ${p.possessiveAdj} family's true purpose.`,
    `Tempered by years of wandering through forgotten ruins and fighting off subterranean horrors, ${p.subject} mastered the deadly art of the ${characterClass}.`,
    `Bound by a solemn oath sworn before the altar of ${p.possessiveAdj} ancestors, ${name} set out to hunt down the fell forces threatening the realm.`,
    `Having survived a treacherous betrayal by a rival merchant house, ${name} forged a new identity bound to honor, blade, and magic.`,
    `When a dragon's flame scorched ${p.possessiveAdj} ancestral guildhall, ${name} vowed never again to stand idle while innocent blood is spilled.`,
    `Inspired by the heroic sagas told by traveling bards, ${name} left behind a quiet farmstead to carve out a legacy worthy of legend.`,
    `After unlocking a long-dormant magical lineage during an unexpected demonic breach, ${name} accepted ${p.possessiveAdj} calling as a ${characterClass}.`,
  ];

  const traits = [
    `Guided by an unshakeable moral compass and a quick wit, ${name} approaches every conflict with tactical precision and unyielding resolve.`,
    `Equipped with battle-tested armor and an acute sense for ambush, ${p.subject} walks with a quiet, lethal grace that inspires allies and unnerves foes alike.`,
    `With a deep reverence for the sacred balance of the world, ${name} brings both veteran combat skill and strategic wisdom to the party.`,
    `Known across the taverns and keeps as a fearless defender, ${name} never backs down from a threat to those in ${p.possessiveAdj} care.`,
    `Possessing a mind that analyzes combat as a grand chess game, ${name} turns even the direst odds into calculated victories.`,
    `Infused with fierce loyalty toward companions, ${name} will cross rivers of fire before letting a comrade fall.`,
    `Quietly observant yet devastatingly decisive in crisis, ${name} balances ancient lore with practical battle prowess.`,
  ];

  const destinies = [
    `Now, drawn by rumors of ancient artifacts and rising darkness, ${name} journeys forward to etch ${p.possessiveAdj} name into the legends of the continent.`,
    `Driven by a thirst for truth and glory, ${name} stands ready to confront whatever dragon, fiend, or tyrant blocks the path ahead.`,
    `With fate calling ${p.object} toward uncharted frontiers, ${name} answers the call to adventure without a shadow of hesitation.`,
    `Bound to a grand destiny foretold in ancient sagas, ${name} fights to restore peace and usher in a new age of heroes.`,
    `Determined to unravel the cosmic mystery behind ${p.possessiveAdj} lineage, ${name} marches into the storm with blade in hand.`,
    `Seeking to rebuild a fallen order of protectors, ${name} travels the shattered roads of the realm in search of worthy allies.`,
    `Pushed forward by the memory of lost loved ones, ${name} swears to be the wall that stands between light and darkness.`,
  ];

  for (let attempt = 0; attempt < 100; attempt++) {
    const origin = origins[Math.floor(Math.random() * origins.length)];
    const point = turningPoints[Math.floor(Math.random() * turningPoints.length)];
    const trait = traits[Math.floor(Math.random() * traits.length)];
    const destiny = destinies[Math.floor(Math.random() * destinies.length)];

    const candidate = `${origin} ${point} ${trait} ${destiny}`;
    if (!lowerExisting.includes(candidate.trim().toLowerCase())) {
      return candidate;
    }
  }

  // Fallback if thousands of backstories exist
  const origin = origins[Math.floor(Math.random() * origins.length)];
  const point = turningPoints[Math.floor(Math.random() * turningPoints.length)];
  const trait = traits[Math.floor(Math.random() * traits.length)];
  const destiny = destinies[Math.floor(Math.random() * destinies.length)];
  return `${origin} ${point} ${trait} ${destiny} Sealed by sacred oath #${Math.floor(Math.random() * 899 + 100)}.`;
}

export const SPELLCASTING_CLASSES: CharacterClass[] = [
  'Wizard',
  'Cleric',
  'Bard',
  'Sorcerer',
  'Warlock',
  'Druid',
  'Paladin',
  'Ranger',
];

export function getSpellSlotsForClass(characterClass: CharacterClass, level: number = 1): number {
  if (['Wizard', 'Cleric', 'Bard', 'Sorcerer', 'Druid'].includes(characterClass)) {
    if (level >= 3) return 4;
    if (level === 2) return 3;
    return 2;
  }
  if (characterClass === 'Warlock') {
    if (level >= 2) return 2;
    return 1;
  }
  if (['Paladin', 'Ranger'].includes(characterClass)) {
    if (level >= 2) return 2;
    return 0;
  }
  return 0;
}

export function randomizeCharacter(
  existingChar: Character,
  playerNumber: number,
  existingNames: string[] = [],
  existingBackstories: string[] = []
): Character {
  const genders: Gender[] = ['Male', 'Female', "I'd rather not say"];
  const gender = existingChar?.gender || genders[Math.floor(Math.random() * genders.length)];
  const randomClass = ALL_CLASSES[Math.floor(Math.random() * ALL_CLASSES.length)];
  const randomRace = ALL_RACES[Math.floor(Math.random() * ALL_RACES.length)];
  const newName = generateRandomName(randomClass, randomRace, existingNames);
  const newStats = rollDndStats();

  const hpByClass: Record<CharacterClass, number> = {
    Barbarian: 15,
    Fighter: 12,
    Paladin: 12,
    Ranger: 11,
    Cleric: 10,
    Druid: 10,
    Monk: 10,
    Rogue: 10,
    Bard: 10,
    Warlock: 10,
    Wizard: 8,
    Sorcerer: 8,
  };

  const acByClass: Record<CharacterClass, number> = {
    Fighter: 16,
    Paladin: 18,
    Barbarian: 14,
    Rogue: 14,
    Wizard: 12,
    Cleric: 16,
    Ranger: 15,
    Bard: 13,
    Warlock: 13,
    Sorcerer: 12,
    Druid: 13,
    Monk: 15,
  };

  const slots = getSpellSlotsForClass(randomClass, 1);

  const avatars: Record<CharacterClass, string> = {
    Fighter: '⚔️',
    Wizard: '🪄',
    Rogue: '🗡️',
    Cleric: '✨',
    Paladin: '🛡️',
    Barbarian: '🪓',
    Bard: '🪕',
    Ranger: '🏹',
    Warlock: '🔮',
    Sorcerer: '⚡',
    Druid: '🌿',
    Monk: '☯️',
  };

  const maxHp = hpByClass[randomClass];
  const backstory = generateFantasyBackstory(newName, randomRace, randomClass, existingBackstories, gender);

  return {
    ...existingChar,
    name: newName,
    gender,
    race: randomRace,
    characterClass: randomClass,
    maxHp,
    hp: maxHp,
    ac: acByClass[randomClass],
    stats: newStats,
    spellSlots: slots,
    maxSpellSlots: slots,
    backstory,
    avatar: avatars[randomClass],
    portraitUrl: getAutoGeneratedPortrait(randomRace, randomClass, newName, gender),
  };
}

export function createDefaultCharacter(
  id: string,
  playerNumber: number,
  characterClass: CharacterClass = 'Fighter',
  race: Race = 'Human',
  isAiControlled: boolean = false,
  existingNames: string[] = [],
  existingBackstories: string[] = [],
  gender?: Gender
): Character {
  const baseStats: Record<CharacterClass, Stats> = {
    Fighter: { str: 16, dex: 13, con: 14, int: 10, wis: 12, cha: 10 },
    Wizard: { str: 8, dex: 14, con: 12, int: 16, wis: 13, cha: 10 },
    Rogue: { str: 10, dex: 16, con: 12, int: 13, wis: 10, cha: 14 },
    Cleric: { str: 14, dex: 10, con: 14, int: 10, wis: 16, cha: 12 },
    Paladin: { str: 16, dex: 10, con: 14, int: 10, wis: 10, cha: 15 },
    Barbarian: { str: 17, dex: 13, con: 15, int: 8, wis: 10, cha: 8 },
    Bard: { str: 10, dex: 14, con: 12, int: 12, wis: 10, cha: 16 },
    Ranger: { str: 12, dex: 16, con: 13, int: 10, wis: 14, cha: 10 },
    Warlock: { str: 9, dex: 13, con: 14, int: 11, wis: 10, cha: 16 },
    Sorcerer: { str: 8, dex: 14, con: 13, int: 10, wis: 10, cha: 16 },
    Druid: { str: 10, dex: 12, con: 14, int: 12, wis: 16, cha: 10 },
    Monk: { str: 11, dex: 16, con: 13, int: 10, wis: 15, cha: 10 },
  };

  const hpByClass: Record<CharacterClass, number> = {
    Barbarian: 15,
    Fighter: 12,
    Paladin: 12,
    Ranger: 11,
    Cleric: 10,
    Druid: 10,
    Monk: 10,
    Rogue: 10,
    Bard: 10,
    Warlock: 10,
    Wizard: 8,
    Sorcerer: 8,
  };

  const acByClass: Record<CharacterClass, number> = {
    Fighter: 16, // Chain shirt + shield
    Paladin: 18, // Chain mail + shield
    Barbarian: 14, // Unarmored defense (10 + dex + con)
    Rogue: 14, // Leather + dex
    Wizard: 12, // Dex
    Cleric: 16, // Scale mail + shield
    Ranger: 15, // Studded leather + dex
    Bard: 13, // Leather + dex
    Warlock: 13, // Leather + dex
    Sorcerer: 12, // Dex
    Druid: 13, // Hide + shield
    Monk: 15, // Unarmored (10 + dex + wis)
  };

  const defaultNames: Record<CharacterClass, string[]> = {
    Fighter: ['Valerius', 'Kaelen', 'Brunhild', 'Garrick'],
    Wizard: ['Eldrin', 'Ignis', 'Lyra', 'Vaelin'],
    Rogue: ['Shadow', 'Corvin', 'Talia', 'Sylas'],
    Cleric: ['Brother Thaddeus', 'Soren', 'Aurelia', 'Vesper'],
    Paladin: ['Sir Gareth', 'Helena', 'Lucian', 'Kael'],
    Barbarian: ['Thorgar', 'Freya', 'Brak', 'Grendel'],
    Bard: ['Callum', 'Melody', 'Orpheus', 'Piper'],
    Ranger: ['Hawk', 'Sylvan', 'Astrid', 'Rowan'],
    Warlock: ['Malakor', 'Morrigan', 'Nyx', 'Dorian'],
    Sorcerer: ['Zarek', 'Ember', 'Zephyr', 'Celeste'],
    Druid: ['Oakley', 'Thorn', 'Willow', 'Bram'],
    Monk: ['Zenon', 'Kenshi', 'Lotus', 'Tao'],
  };

  const name = generateRandomName(characterClass, race, existingNames);
  const maxHp = hpByClass[characterClass];
  const slots = getSpellSlotsForClass(characterClass, 1);

  const avatars: Record<CharacterClass, string> = {
    Fighter: '⚔️',
    Wizard: '🪄',
    Rogue: '🗡️',
    Cleric: '✨',
    Paladin: '🛡️',
    Barbarian: '🪓',
    Bard: '🪕',
    Ranger: '🏹',
    Warlock: '🔮',
    Sorcerer: '⚡',
    Druid: '🌿',
    Monk: '☯️',
  };

  const backstory = generateFantasyBackstory(name, race, characterClass, existingBackstories, gender);

  return {
    id,
    playerName: `Player ${playerNumber}`,
    name,
    gender,
    race,
    characterClass,
    level: 1,
    xp: 0,
    hp: maxHp,
    maxHp,
    ac: acByClass[characterClass],
    stats: baseStats[characterClass],
    spellSlots: slots,
    maxSpellSlots: slots,
    inventory: ['Explorer Pack', 'Healing Potion', '15 Gold Pieces'],
    features: [`${characterClass} Training`],
    backstory,
    avatar: avatars[characterClass],
    portraitUrl: getAutoGeneratedPortrait(race, characterClass, name, gender),
    status: 'Healthy',
    statusEffects: [],
    isAiControlled,
  };
}

// D&D 5E Experience Points (XP) Thresholds Table (Levels 1-20)
export const LEVEL_XP_THRESHOLDS: Record<number, number> = {
  1: 0,
  2: 300,
  3: 900,
  4: 2700,
  5: 6500,
  6: 14000,
  7: 23000,
  8: 34000,
  9: 48000,
  10: 64000,
  11: 85000,
  12: 100000,
  13: 120000,
  14: 140000,
  15: 165000,
  16: 195000,
  17: 225000,
  18: 265000,
  19: 305000,
  20: 355000,
};

// Hit Die info by class for standard HP advancement
export const HIT_DICE_BY_CLASS: Record<CharacterClass, { die: string; dieValue: number; avgRoll: number }> = {
  Barbarian: { die: 'd12', dieValue: 12, avgRoll: 7 },
  Fighter: { die: 'd10', dieValue: 10, avgRoll: 6 },
  Paladin: { die: 'd10', dieValue: 10, avgRoll: 6 },
  Ranger: { die: 'd10', dieValue: 10, avgRoll: 6 },
  Bard: { die: 'd8', dieValue: 8, avgRoll: 5 },
  Cleric: { die: 'd8', dieValue: 8, avgRoll: 5 },
  Druid: { die: 'd8', dieValue: 8, avgRoll: 5 },
  Monk: { die: 'd8', dieValue: 8, avgRoll: 5 },
  Rogue: { die: 'd8', dieValue: 8, avgRoll: 5 },
  Warlock: { die: 'd8', dieValue: 8, avgRoll: 5 },
  Sorcerer: { die: 'd6', dieValue: 6, avgRoll: 4 },
  Wizard: { die: 'd6', dieValue: 6, avgRoll: 4 },
};

/** Get the minimum XP needed to attain a specific level */
export function getXpRequiredForLevel(level: number): number {
  const targetLevel = Math.max(1, Math.min(20, level));
  return LEVEL_XP_THRESHOLDS[targetLevel] ?? 0;
}

/** Compute the XP progression progress between current level and next level */
export function getXpProgressInfo(xp: number = 0, currentLevel: number = 1) {
  const currentFloor = LEVEL_XP_THRESHOLDS[currentLevel] || 0;
  const nextTarget = LEVEL_XP_THRESHOLDS[Math.min(20, currentLevel + 1)] || currentFloor;
  const isMaxLevel = currentLevel >= 20;

  if (isMaxLevel) {
    return {
      currentXp: xp,
      currentLevelFloor: currentFloor,
      nextLevelTarget: currentFloor,
      xpInCurrentBracket: 0,
      xpNeededInBracket: 0,
      xpToNextLevel: 0,
      percent: 100,
      canLevelUp: false,
    };
  }

  const xpNeededInBracket = Math.max(1, nextTarget - currentFloor);
  const xpInCurrentBracket = Math.max(0, xp - currentFloor);
  const xpToNextLevel = Math.max(0, nextTarget - xp);
  const percent = Math.min(100, Math.max(0, Math.round((xpInCurrentBracket / xpNeededInBracket) * 100)));
  const canLevelUp = xp >= nextTarget;

  return {
    currentXp: xp,
    currentLevelFloor: currentFloor,
    nextLevelTarget: nextTarget,
    xpInCurrentBracket,
    xpNeededInBracket,
    xpToNextLevel,
    percent,
    canLevelUp,
  };
}

